### ISSUE TITLE
sync code wrapped in promise

### ISSUE THREAD

**Issue by stropitek** [TeselaGen/ve-sequence-parsers#14]
I'm using genbankToJson and the function does not seem to have any async code (all callbacks passed are executed synchronously)

Therefore I don't understand why the method doesn't just return the parsed genbank synchronously, instead of wrapping it in a Promise or letting the user provide a callback.

**Comment by tnrich** [comment]
Hey @stropitek, again sorry for the delay in getting back to you. I'm going to be updating the issue template so that my name is specifically mentioned for now on...

The reason for the callback based interface is because the xml2js parseString method relied on a callback: 
```js
var parseString = 
require('xml2js').parseString;
parseString(string, function(err, result) {
...
```
I thought it would be simpler if there was a single callback based interface for all of the parsers so we wouldn't have to call some of them differently than others. 

Wrapping it in a promise just allows us to use the handy async await pattern. 

Yeah, maybe there could have been a better way to structure things but it works fine for our needs.

**Comment by stropitek** [comment]
Reading `xml2js`'s documentation I see that it's also synchronous (the callback is called synchronously). I don't really get why they chose a callback api rather than more straightforwardly returning the result.

Anyway that means that all you parsers can actually be synchronous, which would greatly simplify the api!!

**Comment by tnrich** [comment]
Sorry @stropitek but I plan on keeping the interface to this package async.
