### ISSUE TITLE
Genbank file DEFINITION field should populate description

### ISSUE THREAD

**Issue by llynchIDBS** [TeselaGen/ve-sequence-parsers#15]
The DEFINITION line in a genbank file should be read as the description in the JSON.
Perhaps there are other fields where the description might come from but this is the standard place it seems:
https://www.ncbi.nlm.nih.gov/Sitemap/samplerecord.html#DefinitionB

E.g. your test file:
https://github.com/TeselaGen/ve-sequence-parsers/blob/master/src/test/testData/genbank/testGenbankFile.gb
has:
_DEFINITION promoter seq from _pBAD33._

So I think this definitely needs fixing - WDYT @tnrich ?
I could probably fix it and raise a PR, just not sure when I will get to it ... we're coming back to this and picking up a new bio-parsers version in a few weeks, but maybe you'll be able to take a look before that.

Thanks!

**Comment by tnrich** [comment]
@llynchIDBS thanks for raising this issue. I'll look into fixing this. Should be relatively simple. I'll get back to you shortly

**Comment by tnrich** [comment]
Hey @llynchIDBS I've published a new version that handles the DEFINTION field from genbank files by adding a `sequenceData.defnition` property. See https://github.com/TeselaGen/ve-sequence-parsers/blob/master/src/test/jsonToGenbank.test.js#L83 for the test. I didn't want to add it to the .description field because that field could be overwritten by existing "description" comments. 

Let me know if the `.definition` property solves it for you.

Cheers,
Thomas

**Comment by llynchIDBS** [comment]
Thanks @tnrich - that's great.
Should be fine for us that way.
